manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/Xoffio
    - name: inorichi
      url-base: https://github.com/inorichi
    - name: ImSota
      url-base: https://github.com/ImSota
    - name: caksoylar
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: xo-status-fx
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
    - name: zmk-naginata
      remote: ImSota
      revision: main
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
  self:
    path: config
